apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongouser:mongopass@mongodb-service:27017/muchtodo?authSource=admin"
